name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23.0.2'
          distribution: 'oracle'

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export JAVA_HOME=/root/.sdkman/candidates/java/current
            export PATH=$JAVA_HOME/bin:$PATH
            java -jar -Dserver.port=8080 /opt/java/zapvideo-0.0.1-SNAPSHOT.jar
