name: Deploy Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "Deploying to VPS"
#            pkill -f 'java -jar' || echo "Nenhuma aplicação em execução"
            
#            cd /opt/ZapVideo
            
#            git pull origin main
            
#            ./gradlew clean build
#            nohup java -jar build/libs/zapvideo-0.0.1-SNAPSHOT.jar --server.port=8080 > app.log 2>&1 &
